import { Inter } from "next/font/google";
import "@Styles/global.css";
import "@Styles/reset.css";
import StoreProvider from "./storeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Online Celebration",
  description: "Generated by Online Celebration",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className="container">
        <main className="content">
          <StoreProvider>{children}</StoreProvider>
        </main>
        <div id="modal-root" />
      </body>
    </html>
  );
}
